# Generated by Django 3.1.5 on 2021-01-26 10:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photo/', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='MapCoordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_coordinate', models.CharField(max_length=255, verbose_name='Первый координат карты')),
                ('second_coordinate', models.CharField(max_length=255, verbose_name='Первый координат карты')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('name_productions', models.CharField(blank=True, max_length=255, verbose_name='Продукты')),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_number', models.CharField(max_length=255, verbose_name='Номер продукта')),
                ('product_name', models.CharField(max_length=255, verbose_name='Наименование продукта')),
                ('product_photo', models.ImageField(upload_to='photo/', verbose_name='Фото продукта')),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='spisok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок списка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Список',
                'verbose_name_plural': 'Списки',
            },
        ),
        migrations.CreateModel(
            name='punkt_of_spisok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punkt', models.CharField(max_length=255, verbose_name='Пукт')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('spisok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.spisok')),
            ],
            options={
                'verbose_name': 'Пункт',
                'verbose_name_plural': 'Пункт списка',
            },
        ),
    ]
