# Generated by Django 3.1.5 on 2021-01-20 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='spisok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок списка')),
                ('text', models.TextField(verbose_name='Текст спика')),
            ],
            options={
                'verbose_name': 'Список',
                'verbose_name_plural': 'Списки',
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_number', models.CharField(max_length=255, verbose_name='Номер продукта')),
                ('product_name', models.CharField(max_length=255, verbose_name='Наименование продукта')),
                ('product_photo', models.ImageField(upload_to='photo/product', verbose_name='Фото продукта')),
                ('spisok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.spisok', verbose_name='Перечень списка')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
