# Generated by Django 3.1.5 on 2021-01-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_spisok'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='spisok',
        ),
        migrations.AddField(
            model_name='product',
            name='spisok',
            field=models.ManyToManyField(to='product.spisok', verbose_name='Перечень списка'),
        ),
    ]
