# Generated by Django 3.1.5 on 2021-01-23 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='spisok',
            new_name='spisok_title',
        ),
    ]
